### ISSUE TITLE
Xamarin Forms android application stuck while doing login for MFA. (IdentityModel.OidcClient v3.1.2)

### ISSUE THREAD

**Issue by ojasteredesai** [auth0-samples/auth0-xamarin-oidc-samples#37] opened 2020-07-15 15:40 UTC
# Issue Report

Xamarin Forms android application stuck while doing login for MFA. (IdentityModel.OidcClient v3.1.2)

### Description
The application is stuck after entering email id password on auth0 page when performing MFA. 

### Expected behaviour

1. User starts login via calling the _auth0Client.LoginAsync() method
2. User enters valid email id and password credentials and then second factor authentication should start.
3. User enters the code that is received in the email and logs in successfully upon entering the code received in the email.

### Actual behaviour 

Application is getting stuck while navigating for second factor authentication.

### Steps to reproduce the problem

1. Check the MFA option of grant type in advanced settings on application.
2. create a user rule for the application required for customized MFA.
3. Enroll the user for MFA via Auth0 API
4. Challenge the user for MFA and after that try to login. 

### Language / Framework Versions
1. **Language used:** C#
2. **Framework used:** Xamarin forms 

Interop layer for hosting Visual Studio Code debug adapters in Visual Studio

Visual Studio Container Tools Extensions (Preview)   1.0
View, manage, and diagnose containers within Visual Studio.

Visual Studio Tools for Containers   1.0
Visual Studio Tools for Containers

VisualStudio.DeviceLog   1.0
Information about my package

VisualStudio.Foo   1.0
Information about my package

VisualStudio.Mac   1.0
Mac Extension for Visual Studio

Xamarin   16.4.000.309 (d16-4@1d551f9)
Visual Studio extension to enable development for Xamarin.iOS and Xamarin.Android.

Xamarin Designer   16.4.0.475 (remotes/origin/d16-4@ac250f5aa)
Visual Studio extension to enable Xamarin Designer tools in Visual Studio.

Xamarin Templates   16.4.25 (579ee62)
Templates for building iOS, Android, and Windows apps with Xamarin and Xamarin.Forms.

Xamarin.Android SDK   10.1.3.7 (d16-4/d66aed0)
Xamarin.Android Reference Assemblies and MSBuild support.
    Mono: fd9f379
    Java.Interop: xamarin/java.interop/d16-4@c4e569f
    ProGuard: xamarin/proguard/master@905836d
    SQLite: xamarin/sqlite/3.28.0@46204c4
    Xamarin.Android Tools: xamarin/xamarin-android-tools/master@9f4ed4b

Xamarin.iOS and Xamarin.Mac SDK   13.10.0.17 (5f802ef)
Xamarin.iOS and Xamarin.Mac Reference Assemblies and MSBuild support.
### Testing environment

1. **Operating system:** Windows 10
2. **Browser version:** - Android emulator API-28

### Screenshots

![image](https://user-images.githubusercontent.com/22704125/87565156-e8438580-c6de-11ea-9c12-1f53442b83d9.png)

**Filling this, you're helping yourself and repo maintainers in solving your issues quicker! Teamwork makes the dreamwork 🤜🏼🤛🏻**

**Comment by ojasteredesai** [comment] 2020-07-21 04:59
Hello Team, 
Any updates on this

**Comment by frederikprijck** [comment] 2023-03-13 08:32
Sorry for not replying to this sooner, it appears we have missed this issue.

I know it's been a while since you reported this, but regardless I gave this a try and was unable to reproduce this.

Closing because it's been a while and I can not reproduce this. Happy to reopen if this comes up again.

**Closed as completed by frederikprijck** 2023-03-13 08:32 UTC
